name: Update SDK based on proto changes + open PR

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target_branch:
        description: "The branch to update"
        required: true
        type: string
    secrets:
      GOOGLE_API_KEY:
        required: true
      GITHUB_TOKEN:
        required: true

#  workflow_run:
#    workflows: [test]
#    types: [completed]
#    branches: [workflow/update-proto]


jobs:
  run-ai-updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}
          fetch-depth: 0 # Fetch all history for debugging git diff
          token: ${{ secrets.GITHUB_TOKEN }}
          path: sdk

      - name: Checkout ai_updater
        uses: actions/checkout@v4
        with:
          repository: gabegottlob/viam-ai-updater
          path: viam-ai-updater
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tree command
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Setup Python
        run: uv python install

      - name: Create virtual environment (for testing)
        run: uv venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install google-genai pydantic

      - name: Debug Git in SDK Repo
        run: |
          echo "--- Git Log in SDK Repo ---"
          cd sdk
          git log --oneline --graph -n 5
          echo "--- Git Status in SDK Repo ---"
          git status
          echo "--- Current Working Directory (for context) ---"
          pwd
          echo "--- SDK Root Directory passed to ai_updater ---"
          echo "$GITHUB_WORKSPACE/sdk"
          echo "--- Direct git diff command execution (first 5 lines) ---"
          git diff HEAD~1 HEAD -- src/viam/gen ':!*_pb2.py' | head -n 5
        shell: bash

      - name: Run ai-updater
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          cd viam-ai-updater/ai_updater
          uv run python ai_updater.py --debug --work $GITHUB_WORKSPACE/sdk

      - name: Add + Commit + Open PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: '[WORKFLOW] AI update based on proto changes'
          path: sdk
          branch: ${{ inputs.target_branch }}
          delete-branch: true
          base: main
          title: AI update based on proto changes
          body: This is an AI-generated PR to update the SDK based on proto changes.
          assignees: gabegottlob
          reviewers: gabegottlob
          token: ${{ secrets.GITHUB_TOKEN }}
