name: Update SDK based on proto changes + open PR
#For local testing run: act workflow_run -W 'ai_updater/' -s GOOGLE_API_KEY --container-architecture linux/amd64 --bind

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target_branch:
        description: "The branch to update"
        required: true
        type: string
    secrets:
      GOOGLE_API_KEY:
        required: true

#  workflow_run:
#    workflows: [test]
#    types: [completed]
#    branches: [workflow/update-proto]

jobs:
  run-ai-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tree command
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Setup Python
        run: uv python install

      - name: Create virtual environment (for testing)
        run: uv venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install google-genai pydantic

      - name: Run ai-updater
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          cd ai_updater
          python ai_updater.py --debug --test "${ GITHUB_WORKSPACE }"

      - name: Add + Commit + Open PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: '[WORKFLOW] AI update based on proto changes'
          branch: ${{ inputs.target_branch }}
          delete-branch: true
          base: main
          title: AI update based on proto changes
          body: This is an AI-generated PR to update the SDK based on proto changes.
          assignees: gabegottlob
          reviewers: gabegottlob
          token: ${{ secrets.GITHUB_TOKEN }}
